name: realtime_data_model
version: 0.0.6-dev
author: Christopher Best <bestchris@gmail.com>
description: |-
  Use Google Drive Realtime API with drive documents and locally with the same interface.
  Based on the google_drive_realtime package.
homepage: https://github.com/sirctseb/realtime-data-model
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  google_drive_v2_api: '>=0.4.9'
  google_oauth2_client: '>=0.2.14'
  json: '>=0.8.1 <1.0.0'
  logging: '>=0.9.0 <0.10.0'
  logging_handlers: '>=0.5.0 <1.0.0'
  meta: '>=0.8.8 <0.9.0'
dev_dependencies:
  browser: '>=0.9.0 <0.10.0'
  unittest: '>=0.9.0 <0.10.0'
