name: realtime_data_model
version: 0.0.4-dev
author: Christopher Best <bestchris@gmail.com>
description: |-
  Use Google Drive Realtime API with drive documents and locally with the same interface.
  Based on the google_drive_realtime package.
homepage: https://github.com/sirctseb/realtime-data-model
dependencies:
  google_drive_v2_api: 0.3.8
  google_oauth2_client: '>=0.2.14'
  js: '>=0.0.22 <1.0.0'
  meta: 0.6.8
dev_dependencies:
  browser: any
  unittest: any
