name: realtime_data_model
version: 0.0.0-dev
author: Christopher Best <bestchris@gmail.com>
homepage: https://github.com/sirctseb/dart-google-drive-realtime
dependencies:
  js: '>=0.0.22 <1.0.0'
  meta: any
dev_dependencies:
  browser: any
  unittest: any
